@echo off

:: copySlicertoTs.bat "D:\D\SlicerI18n\SlicerPython3\Slicer" "D:\tmp\translatedFiles\es_ES" "es_ES"
:: copySlicertoTs.bat "D:\D\SlicerI18n\SlicerPython3\Slicer" "D:\D\SlicerI18n\SlicerPython3\3DSlicerTranslatedFiles\fr_FR" "fr_FR"


:: %1 is the folder Slicer-Build
:: %2 is the folder tranlated files
:: %3 language

IF "%~1"=="" GOTO Syntax
IF "%~2"=="" GOTO Syntax
IF "%~2"=="" GOTO Syntax


SET slicerfolder=%~1
SET tsfolder=%~2
SET language=%~3
SET ts=.ts

::  copy App 
SET copyfolder=\Applications\SlicerApp\Resources\Translations\qSlicerApp_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%

:: copy QTApp
SET copyfolder=\Base\QTApp\Resources\Translations\qSlicerBaseQTApp_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%

:: copy QTCLI
SET copyfolder=\Base\QTCLI\Resources\Translations\qSlicerBaseQTCLI_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%

:: copy QTCore
SET copyfolder=\Base\QTCore\Resources\Translations\qSlicerBaseQTCore_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%

:: copy QTGUI
SET copyfolder=\Base\QTGUI\Resources\Translations\qSlicerBaseQTGUI_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%

:: copy ModulesCore
SET copyfolder=\Modules\Core\Resources\Translations\qSlicerModulesCore_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%

:: copy QTGUI
SET copyfolder=\Libs\MRML\Widgets\Resources\Translations\qMRMLWidgets_
SET copyfile=%slicerfolder%%copyfolder%%language%%ts%

copy %copyfile% %tsfolder%



:Syntax

ECHO.
ECHO copySlicertoTs.cmd
ECHO copy the translated files generated by Slicer building to another folder.
ECHO Wait for three paramaters
ECHO.
ECHO Usage:  copySlicertoTs "Slicer-Build folder" "tranlated files folder" "language"
ECHO.
ECHO Written by Carlos Luque