@echo off

:: copyTstoSlicer.bat  "D:\tmp\translatedFiles\es_ES" "es_ES" "D:\D\SlicerI18n\SlicerPython3\Slicer" 
:: copyTstoSlicer.bat "D:\D\SlicerI18n\SlicerPython3\3DSlicerTranslatedFiles\es_ES" "es_ES" "D:\D\SlicerI18n\SlicerPython3\Slicer" 


:: %2 is the folder tranlated files 
:: %1 is the folder Slicer-Build
:: %3 language

SET slicerfolder=%~3
SET tsfolder=%~1
SET language=%~2
SET ts=.ts

::  copy App 
SET destination=%slicerfolder%\Applications\SlicerApp\Resources\Translations
SET copyfile=%tsfolder%\qSlicerApp_%language%%ts%   

copy %copyfile% %destination%

:: copy QTApp
SET destination=%slicerfolder%\Base\QTApp\Resources\Translations
SET copyfile=%tsfolder%\qSlicerBaseQTApp_%language%%ts%

copy %copyfile% %destination%

:: copy QTCLI
SET destination=%slicerfolder%\Base\QTCLI\Resources\Translations
SET copyfile=%tsfolder%\qSlicerBaseQTCLI_%language%%ts%

copy %copyfile% %destination%

:: copy QTCore
SET destination=%slicerfolder%\Base\QTCore\Resources\Translations\
SET copyfile=%tsfolder%\qSlicerBaseQTCore_%language%%ts%

copy %copyfile% %destination%

:: copy QTGUI
SET destination=%slicerfolder%\Base\QTGUI\Resources\Translations\
SET copyfile=%tsfolder%\qSlicerBaseQTGUI_%language%%ts%

copy %copyfile% %destination%

:: copy ModulesCore
SET destination=%slicerfolder%\Modules\Core\Resources\Translations\
SET copyfile=%tsfolder%\qSlicerModulesCore_%language%%ts%

copy %copyfile% %destination%

:: copy QTGUI
SET destination=%slicerfolder%\Libs\MRML\Widgets\Resources\Translations\
SET copyfile=%tsfolder%\qMRMLWidgets_%language%%ts%

copy %copyfile% %destination%

:Syntax

ECHO.
ECHO copySlicertoTs.cmd
ECHO copy the translated files generated by Slicer building to another folder.
ECHO Wait for three paramaters
ECHO.
ECHO Usage: copyTstoSlicer "tranlated files folder" "language" "Slicer-Build folder"  
ECHO.
ECHO Written by Carlos Luque